name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm typecheck

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Unit tests
        run: pnpm test

      - name: Upload report
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          path: html

  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Coverage
        run: pnpm test:coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          path: coverage
